/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 22/10/2015, 11:38:18 AM
 */
package view;

import model.Analizador;
import model.Thompson;

/**
 *
 * @author phelipedotjc
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClear = new javax.swing.JButton();
        btnDoAFN = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        lblMain = new javax.swing.JLabel();
        lblAlpha = new javax.swing.JLabel();
        lblRegEx = new javax.swing.JLabel();
        tfAlpha = new javax.swing.JTextField();
        tfRegEx = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador Analizadores Lexicos v0.1");
        setResizable(false);

        btnClear.setText("Limpiar Campos");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDoAFN.setText("Generar AFN");
        btnDoAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoAFNActionPerformed(evt);
            }
        });

        lblMain.setFont(new java.awt.Font("Dialog", 1, 12));
        lblMain.setText("Ingrese el alfabeto y la expresión regular:");

        lblAlpha.setText("Alfabeto");

        lblRegEx.setText("Expresión Regular:");

        taResult.setColumns(20);
        taResult.setRows(5);
        scrollPane.setViewportView(taResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addComponent(lblMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDoAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfRegEx)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegEx)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAlpha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlpha)
                    .addComponent(tfAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegEx)
                .addGap(10, 10, 10)
                .addComponent(tfRegEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoAFN)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoAFNActionPerformed

        //Generacion del AFN
        Thompson afn;
        boolean Errors;

        taResult.setText(null);
        System.out.println("INFO: Generando AFN...");
        Analizador traductor = new Analizador(tfRegEx.getText(), tfAlpha.getText());
        Errors = traductor.isError();

        if (Errors) {
            System.err.println("ERROR: " + traductor.getErrMsg());
        } else {
            afn = traductor.traducir();
            Errors = traductor.isError();

            if (Errors) { 
                System.err.println("ERROR: " + traductor.getErrMsg());
            } else {
                System.out.println("INFO: AFN Generado con éxito");
                System.out.println(afn.imprimir());
                taResult.setText(afn.imprimir());
            }
        }
    }//GEN-LAST:event_btnDoAFNActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfAlpha.setText(null);
        tfRegEx.setText(null);
        taResult.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDoAFN;
    private javax.swing.JLabel lblAlpha;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblRegEx;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField tfAlpha;
    private javax.swing.JTextField tfRegEx;
    // End of variables declaration//GEN-END:variables
}
